language: cpp

os:
 - linux
 - osx

compiler:
 - gcc
 - clang

dist: trusty

env:
 - QT=5  BREW=5
 - QT=5  BREW=ex PPA=ubuntu-sdk-team/ppa
 - QT=51 BREW=ex PPA=beineri/opt-qt511-trusty
 - QT=52 BREW=ex PPA=beineri/opt-qt521-trusty
 - QT=53 BREW=ex PPA=beineri/opt-qt532-trusty
 - QT=54 BREW=ex PPA=beineri/opt-qt542-trusty
 - QT=55 BREW=55 PPA=beineri/opt-qt551-trusty
 - QT=56 BREW=5  PPA=beineri/opt-qt561-trusty
 - QT=57 BREW=ex PPA=beineri/opt-qt57-trusty

matrix:
 exclude:
  - { os: osx, env: QT=5  BREW=ex PPA=ubuntu-sdk-team/ppa      }
  - { os: osx, env: QT=51 BREW=ex PPA=beineri/opt-qt511-trusty }
  - { os: osx, env: QT=52 BREW=ex PPA=beineri/opt-qt521-trusty }
  - { os: osx, env: QT=53 BREW=ex PPA=beineri/opt-qt532-trusty }
  - { os: osx, env: QT=54 BREW=ex PPA=beineri/opt-qt542-trusty }
  - { os: osx, env: QT=57 BREW=ex PPA=beineri/opt-qt57-trusty  }
  - { os: osx, compiler: gcc, env: QT=5  BREW=5 } # Qt 5.6 no longer supports gcc on OS X.
  - { os: osx, compiler: gcc, env: QT=56 BREW=5  PPA=beineri/opt-qt561-trusty } # Qt 5.6 no longer supports gcc on OS X.

before_install:
 - '[[ "$TRAVIS_OS_NAME" != linux || -z "$PPA" ]] || sudo add-apt-repository -y ppa:$PPA'
 - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
 - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'

install:
 - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || sudo apt-get -qy install qt$QT-meta-full'
 - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || sudo apt-get -qy install qt5-qmake qtbase5-dev qttools5-dev qttools5-dev-tools qtscript5-dev qtmultimedia5-dev'
 - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt$BREW'
 - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt$BREW'
 - '[ "$TRAVIS_OS_NAME" != osx ] || brew info openssl'

script:
 - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
 - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || export QT_SELECT=qt5'
 - '[ "$TRAVIS_OS_NAME" != osx ] || export OPENSSL_ROOT_DIR=/usr/local/opt/openssl'
 - mkdir build
 - pushd build
 - '[ "$TRAVIS_OS_NAME" != osx ] || cmake .. -DCMAKE_PREFIX_PATH=`brew --prefix qt$BREW` -DQTERM_ENABLE_SCRIPT_DEBUGGER=On -DQT5=Yes'
 - '[ "$TRAVIS_OS_NAME" != linux ] || cmake .. -DQTERM_ENABLE_SCRIPT_DEBUGGER=On -DQT5=Yes'
 - make VERBOSE=1
 - '[ "$TRAVIS_OS_NAME" != osx ] || make package'
 - popd
