language: cpp

compiler:
 - gcc

before_install:
 - sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
 - sudo apt-get install -qq qt57-meta-full

script:
 - mkdir build
 - cd build
 - cmake .. -DQT5=Yes
 - make
